# Host configuration: gnarbox (NixOS Desktop)
#
# Features: fonts, nix-settings, zsh, editors, git, cli-tools, activation, reaper
# Desktop: gnome, gaming, audio, reaper, alvr
# Host-specific: Boot, networking, users, power management, etc.
{ inputs, ... }:
{
  flake.modules.nixos.gnarbox =
    {
      outputs,
      config,
      pkgs,
      lib,
      meta,
      ...
    }:
    {
      imports =
        (with inputs.self.modules.nixos; [
          # Base features
          fonts
          nix-settings
          zsh
          editors
          git
          cli-tools
          rust
          activation
          # Desktop features
          gnome
          gaming
          audio
          reaper
          alvr
        ])
        ++ [
          # Hardware configuration (auto-generated by nixos-generate-config)
          # Lives outside modules/ because import-tree can't handle modulesPath
          ../../hardware-configs/gnarbox.nix
        ];

      # === Enable nix-ld ===
      # For running dynamically linked executables (needed for bunx, npm binaries, etc.)
      programs.nix-ld.enable = true;

      # === Nixpkgs Configuration ===

      nixpkgs = {
        # Add overlays from flake exports
        overlays = [
          outputs.overlays.unstable
          outputs.overlays.zen-browser
        ];
        # Platform
        hostPlatform = "x86_64-linux";
        # Allow unfree packages (Discord, Steam, Obsidian, etc.)
        config.allowUnfree = true;
      };

      # === Boot Configuration ===

      boot = {
        loader = {
          systemd-boot.enable = true;
          # Cap kernels/initrds kept in the 1G EFI partition. Without this,
          # systemd-boot keeps every generation and eventually fills /boot.
          systemd-boot.configurationLimit = 10;
          efi.canTouchEfiVariables = true;
        };
        kernelPackages = pkgs.linuxPackages_latest;
        # LUKS device configuration
        initrd.luks.devices."luks-2fdf3d82-e78b-42dc-9d5a-a37303f79531" = {
          device = "/dev/disk/by-uuid/2fdf3d82-e78b-42dc-9d5a-a37303f79531";
        };
        # Hibernation support - configure resume device for power button hibernation
        resumeDevice = "/dev/disk/by-uuid/84deb268-57ba-4cfe-ab1a-85a971db89ce";
      };

      swapDevices = [
        {
          device = "/dev/disk/by-uuid/84deb268-57ba-4cfe-ab1a-85a971db89ce";
        }
      ];

      # === Networking ===

      networking = {
        hostName = meta.hostname;
        networkmanager.enable = true;
      };

      # === Localization ===

      time.timeZone = "America/Los_Angeles";

      i18n = {
        defaultLocale = "en_US.UTF-8";
        extraLocaleSettings = {
          LC_ADDRESS = "en_US.UTF-8";
          LC_IDENTIFICATION = "en_US.UTF-8";
          LC_MEASUREMENT = "en_US.UTF-8";
          LC_MONETARY = "en_US.UTF-8";
          LC_NAME = "en_US.UTF-8";
          LC_NUMERIC = "en_US.UTF-8";
          LC_PAPER = "en_US.UTF-8";
          LC_TELEPHONE = "en_US.UTF-8";
          LC_TIME = "en_US.UTF-8";
        };
      };

      # === User Configuration ===

      users.users.bryan = {
        isNormalUser = true;
        description = "Bryan";
        extraGroups = [
          "networkmanager"
          "wheel"
          "plugdev" # ZSA keyboard flashing/connect via keymapp (see hardware.keyboard.zsa)
        ];
        shell = pkgs.zsh;
      };

      # === Security ===

      security.sudo.wheelNeedsPassword = false;

      # === Hardware ===

      hardware.keyboard.zsa.enable = true;

      # === Programs ===

      programs = {
        firefox.enable = true;
        gnupg.agent = {
          enable = true;
          enableSSHSupport = true;
          pinentryPackage = pkgs.pinentry-gnome3;
        };
      };

      # === Services ===

      services = {
        pcscd.enable = true; # Smart card daemon for YubiKey CCID
        printing.enable = true;
        tailscale.enable = true; # tailnet access to the studio Hermes gateway
        # Disable upower - not needed on desktop without batteries
        upower.enable = lib.mkForce false;
        # Power management - prevent auto-sleep for Steam streaming
        logind = {
          settings.Login = {
            HandlePowerKey = "hibernate";
            HandleSuspendKey = "ignore";
            HandleLidSwitch = "ignore";
            IdleAction = "ignore";
            IdleActionSec = 0;
          };
        };
      };

      # === Syncthing ===
      # Uses NixOS native services.syncthing module

      services.syncthing = {
        enable = true;
        user = "bryan";
        group = "users";
        dataDir = "/home/bryan";
        configDir = "/home/bryan/.config/syncthing";
        guiAddress = "127.0.0.1:8384";
        openDefaultPorts = true;
        # Manage devices/folders via Web UI, not declaratively
        overrideDevices = false;
        overrideFolders = false;
      };

      # === Host-specific System Packages ===

      environment.systemPackages = with pkgs; [
        # GPG (GNOME-specific pinentry)
        pinentry-gnome3

        # Media
        vlc

        # Hermes Agent (Nous Research) — client. No local gateway; point it at
        # the studio gateway via ~/.hermes/.env at runtime.
        #   .default → CLI/TUI/ACP (hermes, hermes-acp, hermes-agent)
        #   .desktop → GUI app
        inputs.hermes-agent.packages.${pkgs.stdenv.hostPlatform.system}.default
        inputs.hermes-agent.packages.${pkgs.stdenv.hostPlatform.system}.desktop

        # Upstream's desktop package ships only bin/hermes-desktop — no .desktop
        # entry — so it never appears in the GNOME app grid. Provide one.
        (makeDesktopItem {
          name = "hermes-desktop";
          desktopName = "Hermes";
          comment = "Nous Research Hermes Agent desktop client";
          exec = "hermes-desktop";
          # ponytail: absolute store path in Icon= — works in GNOME. If another DE
          # ignores it, install into share/icons/hicolor/<size>/apps/ instead.
          icon = ./assets/hermes-icon.png;
          terminal = false;
          categories = [
            "Network"
            "Utility"
          ];
        })

        # GUI applications
        keymapp
        obsidian
        vivaldi
        zen-browser

        # Unstable packages
        # NOTE: claude-code temporarily removed - npm package yanked
        # Re-enable when nixpkgs updates: unstable.claude-code

        # GNOME extensions
        gnomeExtensions.hide-top-bar

        # Host-specific packages
        yaak
        libfido2 # FIDO2/U2F tools
        yubioath-flutter # Yubico Authenticator
        yubikey-manager # ykman CLI
      ];

      # === System State ===

      system.stateVersion = "25.05";
    };
}
